ALTER TABLE user MODIFY userid INT AUTO_INCREMENT;
ALTER TABLE data MODIFY dataid INT AUTO_INCREMENT;
ALTER TABLE note MODIFY noteid INT AUTO_INCREMENT;
ALTER TABLE image MODIFY imageid INT AUTO_INCREMENT;